# Generated by Django 5.0.6 on 2024-06-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pictures/default.png", upload_to="profile_pictures/"
            ),
        ),
    ]
